export const MESSAGE_TYPES = {
    GET_MESSAGES_START: "GET_MESSAGES_START",
    GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
    GET_MESSAGES_ERROR: "GET_MESSAGES_ERROR",
    CREATE_MESSAGE_START: "CREATE_MESSAGE_START",
    CREATE_MESSAGE_SUCCESS: "CREATE_MESSAGE_SUCCESS",
    CREATE_MESSAGE_ERROR: "CREATE_MESSAGE_ERROR",
}