export const NOTIFICATION_TYPES =  {
    "GET_NOTIFICATIONS_START": "GET_NOTIFICATIONS_START",
    "GET_NOTIFICATIONS_SUCCESS": "GET_NOTIFICATIONS_SUCCESS",
    "GET_NOTIFICATIONS_ERROR": "GET_NOTIFICATIONS_ERROR",
}